name: "Ccache for gh actions"
description: "A GitHub Action that speeds up compiling for C/C++ projects using ccache."
author: "Hendrik Muhs<hendrik.muhs@gmail.com>"
inputs:
  key:
    description: "An additional key for the cache"
    required: false
  restore-keys:
    description: "An ordered list of keys to use for restoring the cache if no cache hit occurred for key"
    required: false
  max-size:
    description: "Max size of the cache"
    default: "500M"
  verbose:
    description: "Verbosity level: 0 (default), 1 or 2. Ignore for sccache."
    default: 0
  sccache:
    description: "Use sccache https://github.com/mozilla/sccache instead of ccache"
    default: false

runs:
  using: "node16"
  main: "dist/restore/index.js"
  post: "dist/save/index.js"
branding:
  icon: "archive"
  color: "gray-dark"
